speling in configuration -> filteringTermsSchema
ga4gh-beacon/beacon-framework-v2 pull request #51
Opened 2021-08-13 15:41 UTC by mbaudis

Typos, but thereby changing also an enum.

2021-08-17 11:34 UTC, Tom-Shorter requested changes

2021-08-17 11:34 UTC, Tom-Shorter commented on configuration/filteringTermsSchema.json
> +          "description": "Term ID, Field ID or custom term string. For term ID use CURIE syntax where possible.",
I'm not 100% sure about this change, this would also indicate that Field ID should also be changed to field ID as well.

2021-08-17 11:34 UTC, Tom-Shorter commented on configuration/filteringTermsSchema.json
> +            "demographic.ethnicity:subsaharan"
No problems with the proposed change but I think that a better example should be used now. 

Ethnicity is a parameter within the individuals model already and is very unlikely to be applied to anything other than an individual. It might make more sense to use a custom filter property which cannot be found in any default models (I think this example is used in quite a few places throughout the framework).

2021-09-03 11:21 UTC, jrambla approved these changes

2021-09-03 11:25 UTC, merged